In [1]:
import pandas as pd
import numpy as np

In [2]:
from google.colab import files
uploaded = files.upload()

Saving ServeUp_data.xlsx to ServeUp_data.xlsx

In [3]:
df = pd.read_excel("ServeUp_data.xlsx")

In [4]:
df.head()

,Company,Website,Country,Category,Target Customer,Pricing,Key Features,Strengths,Weaknesses,Billing POS,Inventory,Online Ordering,Digital Menu,Analytics,Loyalty Program,Multi Branch,Payment Integration
0,Petpooja,petpooja.com,India,Restaurant POS,"Small Restaurants, Cafes",Paid,"Billing, Inventory, Reports",Easy to use,Limited customization,Yes,Yes,Yes,Yes,Yes,No,Yes,Yes
1,Posist (Restroworks),restroworks.com,India,Restaurant OS,"Small Restaurants, Cafes",Premium,"POS, Analytics, Inventory",Enterprise-grade,Expensive,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes
2,DotPe,dotpe.in,India,QR Ordering,"Cafes, Small Restaurants",Custom,"QR Menu, Ordering",Fast deployment,Limited inventory,No,No,Yes,Yes,Limited,No,No,Yes
3,SlickPOS,slickpos.com,India,Restaurant POS,"Cafes, Small Restaurants",Paid,"Billing, Inventory",Affordable,Fewer integrations,Yes,Yes,No,No,Yes,No,Yes,Yes
4,GoFrugal,gofrugal.com,India,Restaurant POS,"Bakeries, Cafes, Small Restaurants",Paid,"POS, CRM, Inventory",Flexible,Complex setup,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes

In [5]:
df.shape

(55, 17)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55 entries, 0 to 54
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Company              55 non-null     object
 1   Website              55 non-null     object
 2   Country              55 non-null     object
 3   Category             55 non-null     object
 4   Target Customer      55 non-null     object
 5   Pricing              55 non-null     object
 6   Key Features         55 non-null     object
 7   Strengths            55 non-null     object
 8   Weaknesses           55 non-null     object
 9   Billing POS          55 non-null     object
 10  Inventory            55 non-null     object
 11  Online Ordering      55 non-null     object
 12  Digital Menu         55 non-null     object
 13  Analytics            55 non-null     object
 14  Loyalty Program      55 non-null     object
 15  Multi Branch         55 non-null     object
 16  Payment Integration  55 non-null     object
dtypes: object(17)
memory usage: 7.4+ KB

In [7]:
df.describe(include='all')

,Company,Website,Country,Category,Target Customer,Pricing,Key Features,Strengths,Weaknesses,Billing POS,Inventory,Online Ordering,Digital Menu,Analytics,Loyalty Program,Multi Branch,Payment Integration
count,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55
unique,55,55,1,24,16,7,45,45,44,2,2,2,2,3,2,2,2
top,Petpooja,petpooja.com,India,Restaurant POS,"Cafes, Small Restaurants",Paid,"Billing, Inventory",Affordable,Expensive,Yes,Yes,Yes,No,Yes,No,Yes,Yes
freq,1,1,55,12,8,37,6,6,4,40,41,28,33,47,39,42,49

In [8]:
df.isnull().sum()

Company                0
Website                0
Country                0
Category               0
Target Customer        0
Pricing                0
Key Features           0
Strengths              0
Weaknesses             0
Billing POS            0
Inventory              0
Online Ordering        0
Digital Menu           0
Analytics              0
Loyalty Program        0
Multi Branch           0
Payment Integration    0
dtype: int64

In [9]:
df['Category'] = df['Category'].replace({
    'POS System':'Restaurant POS',
    'POS Solution':'Restaurant POS',
    'Cloud POS':'Restaurant POS'
})

In [9]:
df = df.apply(lambda x: x.str.strip() if x.dtype == "object" else x)

In [10]:
df['Category'].unique()

array(['Restaurant POS', 'Restaurant OS', 'QR Ordering',
       'Order Management', 'Ordering Platform', 'POS System', 'ERP & POS',
       'Billing Software', 'Inventory Management', 'ERP + POS',
       'Loyalty Platform', 'Cloud POS', 'Commerce + POS', 'POS Solution',
       'Restaurant Management', 'Restaurant Software', 'Inventory & OMS',
       'CRM Platform', 'Mobile POS', 'QR Menu', 'Online Ordering',
       'Restaurant Platform', 'Bakery ERP', 'Bakery Software'],
      dtype=object)

In [11]:
category_mapping = {
    'Mobile POS': 'Restaurant POS',
    'Restaurant Software': 'Restaurant POS',

    'Restaurant Platform': 'Restaurant OS',
    'Restaurant Management': 'Restaurant OS',

    'QR Ordering': 'Ordering Platform',
    'QR Menu': 'Ordering Platform',
    'Online Ordering': 'Ordering Platform',
    'Order Management': 'Ordering Platform',

    'ERP & POS': 'ERP + POS',
    'Bakery ERP': 'ERP + POS',

    'Inventory & OMS': 'Inventory Management',

    'CRM Platform': 'CRM & Loyalty',
    'Loyalty Platform': 'CRM & Loyalty'
}

df['Category'] = df['Category'].replace(category_mapping)

In [36]:
print(df['Category'].unique())

['Restaurant Pos' 'Restaurant Os' 'Ordering Platform' 'Pos System'
 'Erp + Pos' 'Billing Software' 'Inventory Management' 'Crm & Loyalty'
 'Cloud Pos' 'Commerce + Pos' 'Pos Solution' 'Bakery Software']

In [37]:
category_mapping = {
    'ERP & POS': 'ERP + POS',
    'ERP & Pos': 'ERP + POS',
    'Bakery ERP': 'ERP + POS',
    'Commerce + POS': 'ERP + POS',

    'Mobile POS': 'Restaurant POS',
    'Billing Software': 'Restaurant POS',

    'CRM Platform': 'CRM & Loyalty',

    'Inventory Management': 'ERP + POS',
    'Inventory & OMS': 'ERP + POS',

    'QR Menu': 'Ordering Platform',
    'QR Ordering': 'Ordering Platform',

    'Restaurant Pos': 'Restaurant POS',
    'Restaurant Os': 'Restaurant OS'
}

df['Category'] = df['Category'].replace(category_mapping)

In [38]:
print(df['Category'].value_counts())

Category
Restaurant POS       17
Ordering Platform     9
Erp + Pos             9
Restaurant OS         6
Pos System            4
Crm & Loyalty         3
ERP + POS             2
Cloud Pos             2
Commerce + Pos        1
Pos Solution          1
Bakery Software       1
Name: count, dtype: int64

In [39]:
df.to_csv('ServeUp_Final_Cleaned.csv', index=False)

In [40]:
import plotly.express as px

category_counts = df['Category'].value_counts().reset_index()
category_counts.columns = ['Category', 'Count']

fig = px.bar(
    category_counts,
    x='Category',
    y='Count',
    text='Count',
    title='Competitor Distribution by Category'
)

fig.update_layout(
    xaxis_title='Category',
    yaxis_title='Number of Competitors'
)

fig.show()

In [41]:
print(df['Pricing'].unique())

['Paid' 'Premium' 'Custom' 'Freemium' 'Subscription' 'Free/Paid'
 'Enterprise']

In [42]:
df['Pricing'].value_counts()

Pricing
Paid            37
Subscription     5
Freemium         5
Custom           3
Premium          2
Enterprise       2
Free/Paid        1
Name: count, dtype: int64

In [43]:
pricing_mapping = {
    'Premium': 'Paid',
    'Free/Paid': 'Freemium',
    'Custom': 'Custom Quote',
    'Custom Pricing': 'Custom Quote',
    'Enterprise Plan': 'Enterprise',
    'Subscription Based': 'Subscription',
    'Paid Subscription': 'Subscription'
}

df['Pricing'] = df['Pricing'].replace(pricing_mapping)

In [44]:
df['Pricing'] = df['Pricing'].astype(str).str.strip()

In [45]:
df['Pricing'].value_counts()

Pricing
Paid            39
Freemium         6
Subscription     5
Custom Quote     3
Enterprise       2
Name: count, dtype: int64

In [46]:
import plotly.express as px

pricing_counts = df['Pricing'].value_counts().reset_index()
pricing_counts.columns = ['Pricing', 'Count']

fig = px.pie(
    pricing_counts,
    names='Pricing',
    values='Count',
    hole=0.4,
    title='Pricing Model Distribution'
)

fig.show()

In [47]:
feature_cols = [
    'Billing POS',
    'Inventory',
    'Online Ordering',
    'Digital Menu',
    'Analytics',
    'Loyalty Program',
    'Multi Branch',
    'Payment Integration'
]

feature_counts = {}

for col in feature_cols:
    feature_counts[col] = (df[col] == 'Yes').sum()

feature_counts

{'Billing POS': np.int64(40),
 'Inventory': np.int64(41),
 'Online Ordering': np.int64(28),
 'Digital Menu': np.int64(22),
 'Analytics': np.int64(47),
 'Loyalty Program': np.int64(16),
 'Multi Branch': np.int64(42),
 'Payment Integration': np.int64(49)}

In [13]:
df['Category'].value_counts()

Category
Restaurant Pos          15
Ordering Platform        9
Erp + Pos                9
Restaurant Os            6
Pos System               4
Crm & Loyalty            3
Billing Software         2
Inventory Management     2
Cloud Pos                2
Commerce + Pos           1
Pos Solution             1
Bakery Software          1
Name: count, dtype: int64

In [15]:
df.head()

,Company,Website,Country,Category,Target Customer,Pricing,Key Features,Strengths,Weaknesses,Billing POS,Inventory,Online Ordering,Digital Menu,Analytics,Loyalty Program,Multi Branch,Payment Integration
0,Petpooja,petpooja.com,India,Restaurant Pos,"Small Restaurants, Cafes",Paid,"Billing, Inventory, Reports",Easy to use,Limited customization,Yes,Yes,Yes,Yes,Yes,No,Yes,Yes
1,Posist (Restroworks),restroworks.com,India,Restaurant Os,"Small Restaurants, Cafes",Premium,"POS, Analytics, Inventory",Enterprise-grade,Expensive,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes
2,DotPe,dotpe.in,India,Ordering Platform,"Cafes, Small Restaurants",Custom,"QR Menu, Ordering",Fast deployment,Limited inventory,No,No,Yes,Yes,Limited,No,No,Yes
3,SlickPOS,slickpos.com,India,Restaurant Pos,"Cafes, Small Restaurants",Paid,"Billing, Inventory",Affordable,Fewer integrations,Yes,Yes,No,No,Yes,No,Yes,Yes
4,GoFrugal,gofrugal.com,India,Restaurant Pos,"Bakeries, Cafes, Small Restaurants",Paid,"POS, CRM, Inventory",Flexible,Complex setup,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes

In [48]:
df.to_csv("cleaned_competitors.csv", index=False)

In [49]:
from google.colab import files

files.download("cleaned_competitors.csv")

In [50]:
df['Category'].value_counts()

Category
Restaurant POS       17
Ordering Platform     9
Erp + Pos             9
Restaurant OS         6
Pos System            4
Crm & Loyalty         3
ERP + POS             2
Cloud Pos             2
Commerce + Pos        1
Pos Solution          1
Bakery Software       1
Name: count, dtype: int64

In [51]:
df['Pricing'].value_counts()

Pricing
Paid            39
Freemium         6
Subscription     5
Custom Quote     3
Enterprise       2
Name: count, dtype: int64

In [52]:
import pandas as pd

reviews = {
    'Company': ['Petpooja', 'Restroworks', 'DotPe'],
    'Positive': ['Easy Billing', 'Advanced Features', 'Quick Ordering'],
    'Complaint': ['Support Delays', 'Expensive', 'Limited Inventory']
}

review_df = pd.DataFrame(reviews)

review_df

       Company           Positive          Complaint
0     Petpooja       Easy Billing     Support Delays
1  Restroworks  Advanced Features          Expensive
2        DotPe     Quick Ordering  Limited Inventory

In [53]:
review_df.head()

       Company           Positive          Complaint
0     Petpooja       Easy Billing     Support Delays
1  Restroworks  Advanced Features          Expensive
2        DotPe     Quick Ordering  Limited Inventory

In [54]:
review_df['Complaint'].value_counts()

Complaint
Support Delays       1
Expensive            1
Limited Inventory    1
Name: count, dtype: int64

In [55]:
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from google.colab import files

In [56]:
print("Total Competitors:", len(df))
print("Total Categories:", df['Category'].nunique())
print("Total Countries:", df['Country'].nunique())
print("Total Pricing Models:", df['Pricing'].nunique())

Total Competitors: 55
Total Categories: 11
Total Countries: 1
Total Pricing Models: 5

In [57]:
feature_cols = [
    'Billing POS',
    'Inventory',
    'Online Ordering',
    'Digital Menu',
    'Analytics',
    'Loyalty Program',
    'Multi Branch',
    'Payment Integration'
]

feature_counts = {}

for col in feature_cols:
    feature_counts[col] = (df[col] == 'Yes').sum()

import pandas as pd

feature_df = pd.DataFrame(
    list(feature_counts.items()),
    columns=['Feature','Count']
)

feature_df.sort_values(
    by='Count',
    ascending=False
)

               Feature  Count
7  Payment Integration     49
4            Analytics     47
6         Multi Branch     42
1            Inventory     41
0          Billing POS     40
2      Online Ordering     28
3         Digital Menu     22
5      Loyalty Program     16

In [58]:
import plotly.express as px

fig = px.bar(
    feature_df,
    x='Feature',
    y='Count',
    text='Count',
    title='Feature Availability Across Competitors'
)

fig.show()

In [59]:
df['Target Customer'].value_counts()

Target Customer
Cafes, Small Restaurants              8
Bakeries, Cafes                       7
Cafes, Restaurants                    7
Small Restaurants                     6
Restaurants, Cafes                    5
Tea Shops, Juice Shops                4
Bakeries, Small Restaurants           3
Bakeries, Cafes, Small Restaurants    2
Cafes, Tea Shops                      2
Bakeries, Restaurants                 2
Small Restaurants, Cafes              2
Cafes, Bakeries                       2
Bakeries                              2
Tea Shops, Juice Shops, Cafes         1
Cafes, Tea Shops, Juice Shops         1
Juice Shops, Cafes                    1
Name: count, dtype: int64

In [60]:
import plotly.express as px

category_counts = df['Category'].value_counts().reset_index()
category_counts.columns = ['Category', 'Count']

fig = px.bar(
    category_counts,
    x='Category',
    y='Count',
    text='Count',
    title='Competitor Distribution by Category'
)

fig.show()

In [61]:
pricing_counts = df['Pricing'].value_counts().reset_index()
pricing_counts.columns = ['Pricing', 'Count']

fig = px.pie(
    pricing_counts,
    names='Pricing',
    values='Count',
    title='Pricing Model Distribution'
)

fig.show()

In [62]:
customer_counts = df['Target Customer'].value_counts().reset_index()
customer_counts.columns = ['Customer', 'Count']

fig = px.bar(
    customer_counts,
    x='Customer',
    y='Count',
    text='Count',
    title='Target Customer Segments'
)

fig.show()

In [63]:
strength_counts = df['Strengths'].value_counts().head(15).reset_index()
strength_counts.columns = ['Strength', 'Count']

fig = px.bar(
    strength_counts,
    x='Strength',
    y='Count',
    title='Most Common Competitor Strengths'
)

fig.show()

In [64]:
weakness_counts = df['Weaknesses'].value_counts().head(15).reset_index()
weakness_counts.columns = ['Weakness', 'Count']

fig = px.bar(
    weakness_counts,
    x='Weakness',
    y='Count',
    title='Most Common Competitor Weaknesses'
)

fig.show()

In [65]:
features = [
    'POS',
    'Billing',
    'Inventory',
    'Analytics',
    'Loyalty',
    'CRM',
    'QR',
    'Payments',
    'Multi Branch'
]

for feature in features:
    df[feature] = df['Key Features'].str.contains(
        feature,
        case=False,
        na=False
    ).astype(int)

In [66]:
feature_counts = {}

for feature in features:
    feature_counts[feature] = df[feature].sum()

feature_df = pd.DataFrame(
    list(feature_counts.items()),
    columns=['Feature','Count']
)

fig = px.bar(
    feature_df,
    x='Feature',
    y='Count',
    text='Count',
    title='Feature Availability Across Competitors'
)

fig.show()

In [67]:
opportunities = pd.DataFrame({
    'Opportunity':[
        'WhatsApp Ordering',
        'Bakery Workflow',
        'AI Analytics',
        'Loyalty Engine',
        'Inventory Prediction'
    ],
    'Demand':[9,10,8,7,8],
    'Competition':[3,2,5,6,4]
})

opportunities['Score'] = (
    opportunities['Demand'] -
    opportunities['Competition']
)

opportunities

            Opportunity  Demand  Competition  Score
0     WhatsApp Ordering       9            3      6
1       Bakery Workflow      10            2      8
2          AI Analytics       8            5      3
3        Loyalty Engine       7            6      1
4  Inventory Prediction       8            4      4

In [68]:
fig = px.bar(
    opportunities,
    x='Opportunity',
    y='Score',
    text='Score',
    title='ServeUp Opportunity Scorecard'
)

fig.show()

In [69]:
summary = pd.DataFrame({
    'Metric':[
        'Competitors',
        'Categories',
        'Countries',
        'Pricing Models'
    ],
    'Value':[
        len(df),
        df['Category'].nunique(),
        df['Country'].nunique(),
        df['Pricing'].nunique()
    ]
})

summary

           Metric  Value
0     Competitors     55
1      Categories     11
2       Countries      1
3  Pricing Models      5